[project]
name = "wsml-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "pip>=25.3",
    "playwright>=1.55.0",
    "pydantic>=2.12.5",
    "pyinstrument>=5.1.1",
    "requests>=2.32.5",
    "scalene>=1.5.55",
    "tenacity>=9.1.2",
]

[project.scripts]
letterboxd-scrape = "WSML_code.scraping:main"
letterboxd-scrape-pw = "WSML_code.scraping:main_playwright"
letterboxd-scrape-static = "WSML_code.scraping:main_static"
